name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  buildWindows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Setup Haxe & Neko
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7
          neko-version: 2.4.0

      - name: Verify Haxe & Neko
        run: |
          haxe --version
          neko --version
          where haxelib || where haxe || echo "haxelib/haxe not found on PATH"
        shell: cmd

      - name: Install Haxelib libraries
        run: |
          haxelib setup C:/haxelib
          haxelib install lime
          haxelib install openfl
          haxelib --never install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel-addons
          haxelib install tjson
          haxelib install hxjsonast
          haxelib install hscript-iris
          haxelib git linc_luajit https://github.com/AndreiRudenko/linc_luajit
          haxelib install hscript
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib git hxdiscord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib install hxcpp-debug-server
          haxelib install hxdiscordrpc
          haxelib git flxanimate https://github.com/Dot-Stuff/flxanimate
          haxelib git funkin.vis https://github.com/FunkinCrew/funkVis
          haxelib git grig.audio https://gitlab.com/haxe-grig/grig.audio.git
          haxelib list
        shell: cmd

      - name: Create Version Tag
        run: echo "${{github.runid}}" > VERSION

      - name: Compile
        run: haxelib run lime build windows --app-version="4.0.0-${{ github.runid}}"

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: windowsBuild
          path: export/release/windows/bin
