name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  buildWindows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Setup Haxe & Neko
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7
          neko-version: 2.4.0

      - name: Verify Haxe & Neko
        run: |
          haxe --version
          neko --version
          where haxelib || where haxe || echo "haxelib/haxe not found on PATH"
        shell: cmd

      - name: Install Haxelib libraries
        run: |
          haxelib install hxcpp > /dev/null --quiet
          .\"setup/windows.bat"
        shell: cmd

      - name: Create Version Tag
        run: echo "${{github.runid}}" > VERSION

      - name: Compile
        run: haxelib run lime build windows --app-version="4.0.0-${{ github.runid}}"

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: windowsBuild
          path: export/release/windows/bin
